const getPossibleStocksTypes = {
    REQUEST_SEARCHBAR_INPUT_PENDING: 'REQUEST_SEARCHBAR_INPUT_PENDING',
    REQUEST_SEARCHBAR_INPUT_SUCCESS: 'REQUEST_SEARCHBAR_INPUT_SUCCESS',
    REQUEST_SEARCHBAR_INPUT_FAILED: 'REQUEST_SEARCHBAR_INPUT_FAILED'
}

export default getPossibleStocksTypes;